[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "py_motd"
version = "1.0.0"
dependencies = [
    "ruamel.yaml",
    "rich",
]

[project.scripts]
py_motd = "py_motd.__main__:main"

[tool.setuptools.packages.find]
where = ["."]
